### ISSUE TITLE
Installer website lying to me

### ISSUE THREAD

**Issue by PuksPunni** [uwu/neptune#31]
The installer website says neptune installed successfully, but when I open tidal there is no neptune options in the drop-down menu. Please help

**Comment by Sauleline** [comment]
same here

**Comment by yellowsink** [comment]
did you close and reopen tidal?

**Comment by lopes143** [comment]
Sometimes when TIDAL updates to a major version (ex: 2.38 > 2.39), their file structure changes, and neptune is linked to the old version. The installer says it's installed because it exists, but in fact it's not in the right version (it's in this circumstances that neptune simply vanish after a TIDAL update).
The only solution I found was uninstall TIDAL, going to AppData and deleting all tidal-related folders and reinstall both again.

If you're installing for the first time, then idk :/ (maybe you had TIDAL opened when installing neptune or you didn't restart TIDAL...)

**Comment by twnlink** [comment]
This issue is no longer present due to the existence of the modern neptune installer.
